main: ledennis.pm.PM

name: myPluginManager
version: 1.2
author: LeDennis32
description: Plugin for managing your plugins.

commands:
  pm:
    usage: See /<command>.
    description: Main command. Permission is pm.core
